### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by Balsam-Faysal** [FACG4/FACGTracker#5]
## Acceptance criteria :  
- [ ] Authentication : middle-ware 
- [ ] login hbs
- [ ] login routes : 'back to the page that request login page '
- [ ] Error handling

**Comment by InassTubail** [comment]
we decide to change login way :+1: \
- [x] log in by github *using passport middleware 
- [x] using github straregy
- [x] if cf invited user to register in the website , the first login take his information from github and store it in database , if he make another log in he just logged in without update his information in database , if not invited to register in the website by cf , he can not make log in he will directed to a page the explain some information about codeAcamedy and the link to apply
